### ISSUE TITLE
Debian Jessie support

### ISSUE THREAD

**Issue by holms** [phlipper/chef-percona#127]
Can't use your cookbook on debian jessie

My role:

```
{
   "name": "db",
   "description": "db server",
   "default_attributes": {
   },
   "json_class": "Chef::Role",
   "run_list": [
        "recipe[percona]",
        "recipe[percona::server]"
   ],
   "chef_type": "role",
   "override_attributes": {
   }
}
```

```
[2014-04-13T15:19:25+00:00] INFO: WindowsPackage light-weight resource already initialized -- overriding!
[2014-04-13T15:19:35+00:00] INFO: Resource {:package=>"libmysqlclient-dev"} found, now rewinding it
[2014-04-13T15:19:35+00:00] INFO: Resource {:package=>"percona-server-client-5.5"} found, now rewinding it
[2014-04-13T15:19:35+00:00] INFO: Using non-encrypted password for root, mysql
[2014-04-13T15:19:35+00:00] INFO: Using non-encrypted password for root, mysql
[2014-04-13T15:19:35+00:00] INFO: Using non-encrypted password for debian-sys-maint, system
[2014-04-13T15:19:35+00:00] INFO: Using non-encrypted password for root, mysql
[2014-04-13T15:19:35+00:00] INFO: Using non-encrypted password for debian-sys-maint, system
[2014-04-13T15:19:35+00:00] INFO: Using non-encrypted password for backup, mysql
[2014-04-13T15:19:35+00:00] INFO: Using non-encrypted password for root, mysql
[2014-04-13T15:19:35+00:00] INFO: Using non-encrypted password for root, mysql
[2014-04-13T15:19:35+00:00] INFO: Using non-encrypted password for root, mysql
[2014-04-13T15:19:35+00:00] INFO: Using non-encrypted password for root, mysql
[2014-04-13T15:19:35+00:00] INFO: Using non-encrypted password for replication, mysql
[2014-04-13T15:19:35+00:00] INFO: Using non-encrypted password for root, mysql
[2014-04-13T15:19:35+00:00] INFO: Using non-encrypted password for root, mysql
[2014-04-13T15:19:35+00:00] INFO: Using non-encrypted password for root, mysql
[2014-04-13T15:19:35+00:00] INFO: Using non-encrypted password for root, mysql
[2014-04-13T15:19:44+00:00] ERROR: execute[apt-get-update] (apt::default line 29) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
---- Begin output of apt-get update ----
STDOUT: Hit http://security.debian.org jessie/updates InRelease
Hit http://ftp.uk.debian.org jessie InRelease
Hit http://ftp.uk.debian.org jessie-updates InRelease
Hit http://security.debian.org jessie/updates/main Sources
Hit http://security.debian.org jessie/updates/contrib Sources
Hit http://ftp.uk.debian.org jessie-backports InRelease
Hit http://security.debian.org jessie/updates/non-free Sources
Hit http://ftp.uk.debian.org jessie/main Sources/DiffIndex
Hit http://ftp.uk.debian.org jessie/contrib Sources/DiffIndex
Hit http://ftp.uk.debian.org jessie/non-free Sources/DiffIndex
Hit http://ftp.uk.debian.org jessie/main amd64 Packages/DiffIndex
Hit http://ftp.uk.debian.org jessie/contrib amd64 Packages/DiffIndex
Hit http://ftp.uk.debian.org jessie/non-free amd64 Packages/DiffIndex
Hit http://ftp.uk.debian.org jessie/contrib Translation-en/DiffIndex
Hit http://ftp.uk.debian.org jessie/main Translation-en/DiffIndex
Hit http://ftp.uk.debian.org jessie/non-free Translation-en/DiffIndex
Hit http://ftp.uk.debian.org jessie-updates/main Sources
Hit http://security.debian.org jessie/updates/main amd64 Packages
Hit http://security.debian.org jessie/updates/contrib amd64 Packages
Hit http://security.debian.org jessie/updates/non-free amd64 Packages
Hit http://security.debian.org jessie/updates/contrib Translation-en
Hit http://security.debian.org jessie/updates/main Translation-en
Hit http://security.debian.org jessie/updates/non-free Translation-en
Ign http://repo.percona.com jessie InRelease
Hit http://ftp.uk.debian.org jessie-updates/contrib Sources
Hit http://ftp.uk.debian.org jessie-updates/non-free Sources
Hit http://ftp.uk.debian.org jessie-updates/main amd64 Packages
Ign http://repo.percona.com jessie Release.gpg
Hit http://ftp.uk.debian.org jessie-updates/contrib amd64 Packages
Hit http://ftp.uk.debian.org jessie-updates/non-free amd64 Packages
Ign http://repo.percona.com jessie Release
Hit http://ftp.uk.debian.org jessie-updates/contrib Translation-en
Hit http://ftp.uk.debian.org jessie-updates/main Translation-en
Hit http://ftp.uk.debian.org jessie-updates/non-free Translation-en
Hit http://ftp.uk.debian.org jessie-backports/main Sources
Hit http://ftp.uk.debian.org jessie-backports/contrib Sources
Hit http://ftp.uk.debian.org jessie-backports/non-free Sources
Hit http://ftp.uk.debian.org jessie-backports/main amd64 Packages
Hit http://ftp.uk.debian.org jessie-backports/contrib amd64 Packages
Hit http://ftp.uk.debian.org jessie-backports/non-free amd64 Packages
Hit http://ftp.uk.debian.org jessie-backports/contrib Translation-en
Hit http://ftp.uk.debian.org jessie-backports/main Translation-en
Hit http://ftp.uk.debian.org jessie-backports/non-free Translation-en
Err http://repo.percona.com jessie/main amd64 Packages
  404  Not Found [IP: 74.121.199.234 80]
Ign http://repo.percona.com jessie/main Translation-en
STDERR: W: Failed to fetch http://repo.percona.com/apt/dists/jessie/main/binary-amd64/Packages  404  Not Found [IP: 74.121.199.234 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
---- End output of apt-get update ----
Ran apt-get update returned 100; ignore_failure is set, continuing

================================================================================
Error executing action `run` on resource 'execute[apt-get-update]'
================================================================================


Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '100'
---- Begin output of apt-get update ----
STDOUT: Hit http://security.debian.org jessie/updates InRelease
Hit http://ftp.uk.debian.org jessie InRelease
Hit http://ftp.uk.debian.org jessie-updates InRelease
Hit http://security.debian.org jessie/updates/main Sources
Hit http://security.debian.org jessie/updates/contrib Sources
Hit http://ftp.uk.debian.org jessie-backports InRelease
Hit http://security.debian.org jessie/updates/non-free Sources
Hit http://ftp.uk.debian.org jessie/main Sources/DiffIndex
Hit http://ftp.uk.debian.org jessie/contrib Sources/DiffIndex
Hit http://ftp.uk.debian.org jessie/non-free Sources/DiffIndex
Hit http://ftp.uk.debian.org jessie/main amd64 Packages/DiffIndex
Hit http://ftp.uk.debian.org jessie/contrib amd64 Packages/DiffIndex
Hit http://ftp.uk.debian.org jessie/non-free amd64 Packages/DiffIndex
Hit http://ftp.uk.debian.org jessie/contrib Translation-en/DiffIndex
Hit http://ftp.uk.debian.org jessie/main Translation-en/DiffIndex
Hit http://ftp.uk.debian.org jessie/non-free Translation-en/DiffIndex
Hit http://ftp.uk.debian.org jessie-updates/main Sources
Hit http://security.debian.org jessie/updates/main amd64 Packages
Hit http://security.debian.org jessie/updates/contrib amd64 Packages
Hit http://security.debian.org jessie/updates/non-free amd64 Packages
Hit http://security.debian.org jessie/updates/contrib Translation-en
Hit http://security.debian.org jessie/updates/main Translation-en
Hit http://security.debian.org jessie/updates/non-free Translation-en
Ign http://repo.percona.com jessie InRelease
Hit http://ftp.uk.debian.org jessie-updates/contrib Sources
Hit http://ftp.uk.debian.org jessie-updates/non-free Sources
Hit http://ftp.uk.debian.org jessie-updates/main amd64 Packages
Ign http://repo.percona.com jessie Release.gpg
Hit http://ftp.uk.debian.org jessie-updates/contrib amd64 Packages
Hit http://ftp.uk.debian.org jessie-updates/non-free amd64 Packages
Ign http://repo.percona.com jessie Release
Hit http://ftp.uk.debian.org jessie-updates/contrib Translation-en
Hit http://ftp.uk.debian.org jessie-updates/main Translation-en
Hit http://ftp.uk.debian.org jessie-updates/non-free Translation-en
Hit http://ftp.uk.debian.org jessie-backports/main Sources
Hit http://ftp.uk.debian.org jessie-backports/contrib Sources
Hit http://ftp.uk.debian.org jessie-backports/non-free Sources
Hit http://ftp.uk.debian.org jessie-backports/main amd64 Packages
Hit http://ftp.uk.debian.org jessie-backports/contrib amd64 Packages
Hit http://ftp.uk.debian.org jessie-backports/non-free amd64 Packages
Hit http://ftp.uk.debian.org jessie-backports/contrib Translation-en
Hit http://ftp.uk.debian.org jessie-backports/main Translation-en
Hit http://ftp.uk.debian.org jessie-backports/non-free Translation-en
Err http://repo.percona.com jessie/main amd64 Packages
  404  Not Found [IP: 74.121.199.234 80]
Ign http://repo.percona.com jessie/main Translation-en
STDERR: W: Failed to fetch http://repo.percona.com/apt/dists/jessie/main/binary-amd64/Packages  404  Not Found [IP: 74.121.199.234 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
---- End output of apt-get update ----
Ran apt-get update returned 100


Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/apt/recipes/default.rb

 29: execute 'apt-get-update' do
 30:   command 'apt-get update'
 31:   ignore_failure true
 32:   only_if { apt_installed? }
 33:   not_if { ::File.exists?('/var/lib/apt/periodic/update-success-stamp') }
 34: end
 35:



Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/apt/recipes/default.rb:29:in `from_file'

execute("apt-get-update") do
  action "run"
  ignore_failure true
  retries 0
  retry_delay 2
  guard_interpreter :default
  command "apt-get update"
  backup 5
  returns 0
  cookbook_name :apt
  recipe_name "default"
  not_if { #code block }
  only_if { #code block }
end



[2014-04-13T15:19:48+00:00] WARN: This recipe uses search. Chef Solo does not support search unless you install the chef-solo-search cookbook.
[2014-04-13T15:19:48+00:00] WARN: This recipe uses search. Chef Solo does not support search unless you install the chef-solo-search cookbook.
[2014-04-13T15:19:48+00:00] INFO: package[ncurses-dev] is a virtual package, actually acting on package[libncurses5-dev]

================================================================================
Error executing action `install` on resource 'package[percona-server-client-5.5]'
================================================================================


Chef::Exceptions::Package
-------------------------
No version specified, and no candidate version available for percona-server-client-5.5


Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/mysql/recipes/client.rb

 46:   package mysql_pack do
 47:     action :install
 48:   end
 49: end



Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/mysql/recipes/client.rb:46:in `block in from_file'

package("percona-server-client-5.5") do
  action [:install]
  retries 0
  retry_delay 2
  guard_interpreter :default
  options "--force-yes"
  package_name "percona-server-client-5.5"
  cookbook_name :mysql
  recipe_name "client"
end



[2014-04-13T15:20:00+00:00] INFO: Running queued delayed notifications before re-raising exception
[2014-04-13T15:20:00+00:00] ERROR: Running exception handlers
[2014-04-13T15:20:00+00:00] ERROR: Exception handlers complete
[2014-04-13T15:20:00+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2014-04-13T15:20:00+00:00] ERROR: package[percona-server-client-5.5] (mysql::client line 46) had an error: Chef::Exceptions::Package: No version specified, and no candidate version available for percona-server-client-5.5
[2014-04-13T15:20:00+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by phlipper** [comment]
Official Debian support for 7.8 was added in #265. _Jesse_ is still not released, but when it is, and when the Percona repository has packages, I will add tests and official support.
